Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'comm')

# add the general drivers.
src = Split("""
sdp.pb.c
test.c
""")

CPPPATH = [cwd]

group = DefineGroup('protocal', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
