Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'fprint')

# add the general drivers.
src = Split("""
fprint.c
""")

CPPPATH = [cwd]

group = DefineGroup('fprint', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
